P_Website /config/routes.rb
PWebsite::Application.routes.draw do

  resources :organisations

   resources :comments

  devise_for :users

  resources :events

  root :to => "p_core#home"

  match '/resources', :to => "p_core#resources"

  match 'whatishere', :to => "p_core#whatishere"

  match '/contactus', :to => "p_core#contactus"
  
  
  match '/plants', :to => "p_core#plants"
  
  match '/birds', :to => "p_core#birds"
  
  match '/fungi', :to => "p_core#fungi"
  
  match '/butterflies', :to => "p_core#butterflies"
  

end

P_Website /app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :details, :event_id
  validates_presence_of :event_id, :details, :author
  belongs_to :event
  
end

P_Website /app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :title
  validates_presence_of :title, :date, :description
  validates_uniqueness_of :title
  has_many :comments, :dependent => :destroy
  
end

P_Website /app/models/organisation.rb
class Organisation < ActiveRecord::Base
  attr_accessible :description, :title
end

P_Website /app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

P_Website /app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

P_Website /app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new(event_id: params[:event_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

P_Website /app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

P_Website /app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organisations }
    end
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    @organisation = Organisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find(params[:id])
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render json: @organisation, status: :created, location: @organisation }
      else
        format.html { render action: "new" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation = Organisation.find(params[:id])
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url }
      format.json { head :no_content }
    end
  end
end

P_Website /app/controllers/p_core_controller.rb
class PCoreController < ApplicationController
  def home
    @title = "Home"
  end

  def resources
    @title = "Resources"
  end

 
  
  def whatishere
    @title = "What is here?"
  end


  def contactus
    @title = "Contact us"
  end
end

P_Website /app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Mole Valley Natural History"
    if @title.nil?
      base_title
    else
      "#{base_title}|#{@title}"
    end
  end
end

P_Website /app/helpers/comments_helper.rb
module CommentsHelper
end

P_Website /app/helpers/events_helper.rb
module EventsHelper
end

P_Website /app/helpers/organisations_helper.rb
module OrganisationsHelper
end

P_Website /app/helpers/p_core_helper.rb
module PCoreHelper
end

P_Website /app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :event_id %>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

P_Website /app/views/comments/edit.html.erb
<section id='edit'><h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>
</section>

P_Website /app/views/comments/index.html.erb
<h1 align='center'><u>Listing Comments</u></h1>

<table border='1' align='center' cellpadding='5'>
  <tr>
    <th>Event</th> 
    <th>Details</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>

  <tr>
    <td><%= comment.event.title %></td>
    <td><%= comment.details %></td>
    <td><%= comment.author %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

P_Website /app/views/comments/new.html.erb
<section id='new'><h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>
</section>

P_Website /app/views/comments/show.html.erb
<section id='show'><p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @comment.event.title %>
</p>

<p>
  <b>Details:</b>
  <%= @comment.details %>
</p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>
</section>

P_Website /app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

P_Website /app/views/events/edit.html.erb
<section id='edit'><h1>Editing Event</h1>

<%= render 'form' %>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</section>

P_Website /app/views/events/index.html.erb
<article>
  <h1 align= 'center'>Natural History Related Events in Mole Valley</h1>

	<section id="intro">
	<p>
  Mole Valley has a lively and active community of natural history enthusiasts. There are events
  that suite all levels of experience. We provide here some links that will keep you up to date
  with natural history related activities in Mole Valley.
	</p>
	</section>

	<section id="body">
	<table cellpadding= 10px>
		<tr>
			<td>
    <%= image_tag "butterflies/Adonis-Blue-face.jpg", :class => 'butterfliesLeft', :title => 'Adonis Blue face on. Copyright: Jeremy Early',:alt => "Adonis Blue butterfly face on", :height => '150',  :width => '250'%></td>

  	<td><p>
    The RSPB Dorking and District Local Group organise regular events throughout the year that are
    open to all. You do not need to be an expert birdwatcher. Indeed you will find many are ideal
    for those that are wanting to get started. An up to date programme of events can be found
    <%= link_to("here", "http://www.rspb.org.uk/groups/dorkinganddistrict/events/", {:target => "_blank"}) %>.
  	</p></td></tr>

	<tr><td><%= image_tag "Adders-dancing.jpg", :class => 'butterfliesRight',:title => 'Male Adders dancing.Copyright:Jeremy Early', :alt => 				"Male Adders dancing", :height => '150',  :width => '250' %></td>
	
	<td><p>
    Amphibians and Reptiles are important indicators of habitat quality. The Surrey Amphibian and Reptile
    Group is an extremely active and enthusiastic group that provides important support for some of our
    most threatened habitats. An up to date list of their events can be found
    <%= link_to("here", "http://surrey-arg.org.uk/SARG/30000-CommitteeTools/calendar/SARGcalendar.asp", {:target => "_blank"}) %>.
  	</p></td></tr></table>
<hr noshade>
	</section>
</article>


<section id="list">
<h2><u>Listing Events</u></h2>

<table border='1' align='center' cellpadding='5'>
  <tr>
    <th>Title</th> 
	<th>Date</th>  
	<th>Description</th>
    <th></th>
	<% if user_signed_in?%> 
    	<th></th>
    	<th></th>
	<%end%>	
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.date %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
	<% if user_signed_in?%> 
    	<td><%= link_to 'Edit', edit_event_path(event) %></td>
    	<td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in?%> 
	<%= link_to 'New Event', new_event_path %>
<%end%>
</section>

P_Website /app/views/events/new.html.erb
<section id='new'><h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
</section>

P_Website /app/views/events/show.html.erb
<section id='show'><p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

	<%= link_to 'Show Comments', comments_path %> |

<% if user_signed_in?%> 
	<%= link_to 'Edit', edit_event_path(@event) %> |
	<%= link_to 'New Comment', new_comment_path(event_id: @event) %> |
<%end%> 
<%= link_to 'Back', events_path %>
</section>

P_Website /app/views/layouts/_footer.html.erb
<footer id="page_footer">
  &copy; <%= Time.now.year %> Mole Vally Natural History
</footer>

P_Website /app/views/layouts/_header.html.erb
<header id="page_header" role="banner">
	<nav id="utility">
		<% if user_signed_in? %>
		    Signed in as <%= current_user.email %>: 
		    <%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
		<% else %>
			    <%= link_to "Sign up", new_user_registration_path %> or 
	            <%= link_to "sign in", new_user_session_path %>
		<% end %>
	</nav>
	<%= image_tag "banner.png", :class => 'main-image', :height => '150', :width => '998' %>
</header>

P_Website /app/views/layouts/_navigation.html.erb
<nav id="main_nav" role="navigation">
	<ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Events", events_path %></li>
      <li><%= link_to "What is here?", whatishere_path %></li>
      <li><%= link_to "Resources", resources_path %></li>
      <li><%= link_to "Organisations", organisations_path %></li>
      <li><%= link_to "Contact us", contactus_path %></li>
	</ul>
</nav>

P_Website /app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	 <meta charset="utf-8">
	 <title><%= title %></title>
	 <%= stylesheet_link_tag "application", :media => "all"%>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
</head> 
<body>
	
	<div id="container">
		<%= render 'layouts/header'%>
	
			<p class="notice"><%=notice%></p>
			<p class="alert"><%=alert%></p>
		
			<%= render 'layouts/navigation' %>
	
			<%= yield %>
	
			<%= render 'layouts/footer'%>
	</div>
</body>
</html>

P_Website /app/views/organisations/_form.html.erb
<%= form_for(@organisation) do |f| %>
  <% if @organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% @organisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

P_Website /app/views/organisations/edit.html.erb
<section id='edit'>
<h1>Editing Organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>
</section>

P_Website /app/views/organisations/index.html.erb
<section id="list">
<h1>Listing Organisations</h1>

<table border='1' align='center' cellpadding='5'>
  <tr>
    <th>Title</th>
    <th>Description</th> 
    <th></th>
<% if user_signed_in?%> 
    <th></th>
    <th></th>
<%end%>
  </tr>

<% @organisations.each do |organisation| %>
  <tr>
    <td><%= organisation.title %></td>
    <td><%= organisation.description %></td>
    <td><%= link_to 'Show', organisation %></td>
	<% if user_signed_in?%> 
    <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
    <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
	<%end%>
<% end %>
</table>

<br />
<% if user_signed_in?%> 
<%= link_to 'New Organisation', new_organisation_path %>
<%end%>
</section>

P_Website /app/views/organisations/new.html.erb
<section id='new'>

<h1>New Organisation</h1>
<%= render 'form' %>

<%= link_to 'Back', organisations_path %>
</section>

P_Website /app/views/organisations/show.html.erb
<section id='show'>
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @organisation.title %>
</p>

<p>
  <b>Description:</b>
  <%= @organisation.description %>
</p>


<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>
</section>

P_Website /app/views/p_core/contactus.html.erb
<article>
  <h1 align='center'>Contact Us</h1>

  <%= image_tag "Denbies-Hillside.jpg", :class => "contact", :title => 'Denbies Hillside. Copyright: Jeremy Early', :alt => "Denbies Hillside near Dorking", :height => '200',  :width => '300' %>
	
	<section id="body">
  <p>
    We are always looking for additional support. A contact point is currently being arranged (February 2012)
    and will be added as soon as possible. Do get in touch if you would either like to offer help or
    if you would like some advice on nature conservation in Mole Valley.
  </p>
	</section>
	<section id="note">
  <p>
    N.B. This page is currently being revised and an updated version will be provided shortly.
  </p>
	</section>
</article>

P_Website /app/views/p_core/home.html.erb
<article>
  <h1 align='center'>Mole Valley's Natural History</h1>

<section id= "body">
  <p>
    Welcome to Mole Valle's Natural History. Mole Valley has stunning landscapes with a natural history that is
    internationally
    and nationally important. We hope this site will help you appreciate the value of the district's natural
    phenomena, and
    encourage greater care and appreciation of this very special place. The natural beauty of Mole Valley's
    landscape has
    influenced and inspired many artists, writers and poets including John Keats and Jane Austen.
  </p>
</section>


  <%= image_tag "broadwoods_folley.jpg", :class => 'MoleValley', :alt => "Broadwood's Folley", :hieght=>'300', :width=>'250'%>


<section id= "body2">
  <p>
    The rich landscape of Mole Valley is comprised of four distinct landscape types or character areas formed by the
    underlying
    geology;
    <a href="http://www.naturalengland.org.uk/ourwork/farming/funding/ecs/sitings/areas/114.aspx" target="_blank">Thames Basin
      Lowlands</a>,
    <a href="http://www.naturalengland.org.uk/ourwork/landscape/englands/character/areas/north_downs.aspx" target="_blank">North Downs</a>,
    <a href="http://www.naturalengland.org.uk/ourwork/landscape/englands/character/areas/wealden_greensand.aspx" target="_blank">Wealden
      Greensand</a> and the
    <a href="http://www.naturalengland.org.uk/ourwork/landscape/englands/character/areas/low_weald.aspx" target="_blank">Low
      Weald</a>.
    Perhaps most dominant and significant is the
    chalk escarpment of the North Downs, home to
    <a href="http://www.nationaltrust.org.uk/box-hill/" target="_blank">Boxhill</a>,
    which crosses the District and can be viewed from as far away as the
    South Downs. The North Downs are paralleled to the South by an undulating and heavily wooded greensand ridge rising
    to
    <a href="http://www.nationaltrust.org.uk/home/item258348/" target="_blank">Leith Hill</a>
    in the west of the District. South of this is the gently undulating Weald which is more extensively wooded in the
    South
    West of the District. To the North of the District, the Thames Lowland Basin acts as the interface between the
    countryside and
    urban edge and is largely broad and flat with strong field patterns and wooded shaws.
  </p>

  <p>
    The District's name sake, the
    <a href="http://en.wikipedia.org/wiki/River_Mole" target="_blank">River Mole</a>,
    carves its path, starting near Gatwick as a collection of small tributaries in the
    Weald before carving through the steep sided valley of the North Downs, creating the Mole Gap, before extending
    beyond
    Leatherhead and Fetcham to meet the Thames to the North.
  </p>

  <p>
    Such is the importance of the District it is covered by an array of landscape designations including a European
    designation of
    an
    <acronym title="Special Area of Conservation"><a href="http://www.jncc.gov.uk/protectedsites/sacselection/sac.asp?EUcode=UK0012804" target="_blank">SAC</a></acronym>,
    <acronym title="Site of Special Scientific Interest"><a href="http://www.sssi.naturalengland.org.uk/Special/sssi/searchresults.cfm?sssi_name=&amp;frmcounty=1039" target="_blank">SSSI&#8217;s</a></acronym>,
    <acronym title="Sites of Nature Conservation Importance">SNCI&#8217;s</acronym>,
    <acronym title="National Nature Reserve"><a href="http://www.cityoflondon.gov.uk/Corporation/LGNL_Services/Environment_and_planning/Parks_and_open_spaces/Ashtead_Common" target="_blank">NNR</a></acronym>,
    <acronym title="Local Nature Reserve"><a href="http://www.molevalley.gov.uk/index.cfm?articleid=5088" target="_blank">LNR&#8217;s</a></acronym>
    and an
    <acronym title="Special Protection Area"><a href="http://www.surreywildlifetrust.org.uk/Default.asp?mainmenu=ourplaces&amp;SiteID=%7bD78D43CA-91DF-4C6C-A031-0C97ED85B642%7d&amp;EntityID=%7bD78D43CA-91DF-4C6C-A031-0C97ED85B642%7d" target="_blank">SPA</a></acronym>.
  </p>
</section>
<section id= "body3">
  <p>
    The district is one of most wooded parts of Surrey and England with 30.5% woodland cover compared against a national
    average of
    7.5 %. This, in part, is made up of nearly 4000Ha of Broadleaf Woodland, some of which is ancient, and, just over
    2000Ha of
    mixed woodland.
  </p>

  <p>
    The presence of a rich and varied underlying
    <a href="http://www.landis.org.uk/soilscapes" target="_blank">geology</a>
    means the Mole Valley district is home to a rich array of
    <%= link_to "species", whatishere_path %> and
    <a href="http://www.surreycc.gov.uk/sccwebsite/sccwspages.nsf/LookupWebPagesByTITLE_RTF/Surrey+Biodiversity+Action+Plan?opendocument" target="_blank">habitats</a>
    including chalk grassland, lowland heath, wood pasture, and dry acid grassland to name a few, as well as the UK’s
    only
    native <%= link_to "Boxwood", plants_path %>
    population and strong populations of the
    <%= link_to "Purple Emperor butterfly", butterflies_path %>.
    Some of these important and impressive
    habitats and landscape features can be accessed easily from the District's 
    towns. Mole Valley District Council
    has produced a
    booklet with a number of walks to enable you to enjoy this landscape and is available from
    <a href="http://www.molevalley.gov.uk/index.cfm?articleid=3594" target="_blank">here</a>.
  </p>

  <p>
    The District is ecologically important due to the presence of many species, habitats and high area of woodland
    cover.
    It is our aim to support the drive to conserve biodiversity for future generations and to highlight the essential
    role
    it
    plays in maintaining our living conditions through providing
    <a href="http://www.ecosystemservices.org.uk/ecoserv.htm" target="_blank">ecosystem services</a>
    such as climate regulation, pollination,
    water purification, genetic resources and flood control.
  </p>

  <p>
    We hope the information here inspires you to explore the landscape, its habitats and identify species and appreciate
    its
    value and beauty. We ask that you respect the countryside by following the
    <a href="http://www.countrysideaccess.gov.uk/things_to_know/countryside_code" target="outside_link">countryside
      code</a>
    and take memories and experiences and leave nothing but footprints.
  </p>
	<p>
	    This site has been prepared by, and is maintained by Mole Valley's Natural Conservation Group. This group has
	    representatives
	    from the organisations listed below. The
	    <%= link_to "organisations", organisations_path %>
	    have an interest in Mole Valley's natural history and are responsible
	    for managing areas of the District's rich and varied landscape. Opportunities exist to get involved with these
	    organisations
	    or the Mole Valley nature conservation groups; if you feel inspired or have a keen interest then please contact them
	    directly.
	  </p>
</section>
</article>

P_Website /app/views/p_core/whatishere.html.erb
<article>
  <h1 align = 'center'>What You Can See</h1>

  
	<%= image_tag "Mute_Swan_heads.jpg", :class => 'Swan', :alt => "Mute Swans", :hieght =>'125', :width =>'225' %>
	<section id="main">
	  <p>
	    About 60 different kinds of butterfly occur in Britain. More than half of them can be
	    seen in Mole Valley, including several nationally scarce butterflies of chalk
	    grassland and woodland. The high number of species found locally reflects the location of Mole
	    Valley in the warm south east corner of England, and the variety of habitats.
	    Fewer species can survive in the north of Britain, although some are moving
	    northwards as a result of climate change.
	  </p>
	 </section>
<section id="sidebar">	<p><u>
    You can find here links to information on a range of characteristic species
    that are found in Mole Valley.
  	</u></p>
<ul>
  <li><%= link_to "Birds", birds_path %>

  <li>Bats

  <li>Dragonflies and Damselflies

  <li><%= link_to "Fungi", fungi_path %>

  <li>Moths

  <li><%= link_to "Plants", plants_path %>
	
  <li><%= link_to "Butterflies", butterflies_path %>
</ul>
</section>

 
 
</article>